---
title: "PhD Retreat"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Schedule

<br> 

#### Day 1 
2024-05-21 

<br> 

| Time     | Activity                                     | 
|:---------|:---------------------------------------------|
| 12:00         | Arrival and mingle                           |
| 12:30 - 13:30 | Lunch                                        |
| 13:30 - 14:50 | **Longer Presentations I** (20 min each) <br> Presenters: Luise, Sophie, Martin, Markus <br> Moderator: Oskar P. |
| 14:50 - 15:15 | Fika                                         |
| 15:15 - 15:50 | **Lightning Talks I** (5 min sharp)  <br> Presenters: Anton, Sara, Klara, Maria, Asya, Simon <br> Moderator: Luise |
| 15:50 - 16:30 | **Longer Presentations II** (20 min each) <br> Presenters: Oskar P., Kristin <br> Moderator: Emelie |
| 16:30 - 17:30 | **Workshop**: Introduction to Life-Hacking <br> Moderator: Martin               |

<br> 
		
#### Day 2
2024-05-22

<br> 

| Time          | Activity                                                                            | 
|:--------------|:------------------------------------------------------------------------------------|
| 09:00 - 09:45 | **Lightning Talks II** (5 min sharp) <br> Presenters: Theo, Priyanka, Rebecca, Robin, Oskar B., Emelie <br> Moderator: Markus |
| 09:45 - 10:30 | Fika                                                                                |
| 10:30 - 11:45 | **Workshop**: The elevator pitch - How can I communicate my research quickly? <br> Moderator: Sophie |
| 11:45 - 12:45 | Lunch                                                                               |
| 13:00         | Departure                                                                           |


<br> 

#### Before the conference: 

<br> 

1. Enter the title of your presentation in this [table](https://docs.google.com/document/d/17HDhbzRIlMi85yy9KSGG6ZQh80bPh-5J9mZiqejIz6s/edit) by May 15th, 2024.
2. Please make sure to upload your presentation slides to this [folder](https://www.google.com/url?sa=j&url=https%3A%2F%2Fwww.dropbox.com%2Fscl%2Ffo%2Fwsy4fo2msaptcr38h8xjw%2FAJeNjsQe0v0p5e6G8Hnulow%3Frlkey%3Dn1hhxua6hmklea9ctk47r97n1%26dl%3D0&uct=1714469077&usg=U4PVoNChnX900JMg9VaxXfj6YwE.&source=editors) by May 20th, 2024. 
3. For the workshop on day two, you are ask to prepare a 30 second elevator pitch of your current research (idea).

<br> 
<br> 
